version: '2'

services:
    youtrack:
        build:
            context: .
        image: esycat/youtrack
        container_name: youtrack
        restart: always
        ports:
            - 80:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /data/youtrack:/var/lib/youtrack
            - /data/youtrack/conf:/opt/youtrack/conf
